### ISSUE TITLE
Problem running the last version for MAC (2021-05-10)

### ISSUE THREAD

**Issue by StefanoPallotti** [jielab/pageant#4]
Running the last version for MAC (2021-05-10) the following warning is reported (and generates an empty genetic report file):
**ImportError: Unable to find zbar shared library**

Attached the log file 

[20210511153254.log](https://github.com/jielab/pageant/files/6459536/20210511153254.log)

**Comment by asassheng** [comment]
To install the zbar shared library, you can run this command in terminal:
     `brew install zbar`
Or we will manually add the needed file in the next PAGEANT version.

**Comment by StefanoPallotti** [comment]
Hi Zhisheng, 

thanks for the prompt reply.

Maybe it would be better to manually add the file in order that users can download a 'ready to use' tool as it was the previous PAGEANT version.

Kind regards.

Stefano

**Comment by jielab** [comment]
Dear Stefano: yes, Zhi-Sheng is adding whatever libraries needed so that PAGEANT is ready to out, out of the box. I hope that he will upload the updated version shortly.

Best regards,
Jie
