### ISSUE TITLE
Problem running the mac version 05_12_2021 

### ISSUE THREAD

**Issue by StefanoPallotti** [jielab/pageant#5]
Dear all,

there's still some issues running the last version for mac (05_12_2021).

**ERROR: Error: Failed to load dynlib/dll '/var/folders/yh/vg66y9fj70s8365nnh7464p40000gn/T/_MEIQGhQPY/libzbar.dylib'. Most probably this dynlib/dll was not found when the application was frozen., analysis falied.

OSError: dlopen(/var/folders/yh/vg66y9fj70s8365nnh7464p40000gn/T/_MEIQGhQPY/libzbar.dylib, 6): Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.9.dylib

PyInstallerImportError: Failed to load dynlib/dll '/var/folders/yh/vg66y9fj70s8365nnh7464p40000gn/T/_MEIQGhQPY/libzbar.dylib'. Most probably this dynlib/dll was not found when the application was frozen.**

Attached the log file 

Best.

Stefano

[20210514103107.log](https://github.com/jielab/pageant/files/6477583/20210514103107.log)

**Comment by jielab** [comment]
Zhi-Sheng, please make sure that you resolve this issue and upload the correct version, TODAY!!! Thanks!
